### PR TITLE
Automatic login to training app

### PR DESCRIPTION
**Pull request by Ezmeyers**
Added login to training app from tracker-capture sidebar and through broadcast receiver on training startup, amended readme, added login flag hotfix for errors logging in from tracker

### CODE REVIEW

**Comment by sunbiz** [comment]
@Ezmeyers , the review comments from https://github.com/iupui-soic/dhis2-android-trackercapture/pull/1 are not addressed. It still has many changes that are not required.

**Comment by Ezmeyers** [comment]
I am not sure if you received my comments on them. I will re-paste them here. I am not sure why, but my comments say "pending" on the other thread. I posted them this morning.

In regards to the manifest:
Hello, I just want to clarify, did you mean the revert org.hisp.dhis.android.trackercapture.export.DBProvider back to android:name=".export.DBProvider" as well as fixing the formatting? I did not see other changes

In regards to other comments, I need some clarification:
When specifying "No change is required," on the PR in general, do you mean, "No change is required, remove those modifications," or "No change is required, the request is acceptable"

As far as the app/gradle changes, they are auto-generated, I guess? I do not know anything about it, since I never modified them myself. How would you have me "undo" these changes.

Thanks!

**Comment by sunbiz** [comment]
I mean, those files don't need any changes for this task. Just revert the changes before commit, if there are changes to any files that are not intended.
I also mean, not to change formatting, when its not necessary. Also to add back the full package name, as before.

**Comment by Ezmeyers** [comment]
I spent a while trying to change the gradlew files back. They immediately revert when I push to github. Since I am on a Linux computer, the Unix formatted line endings are automatically generated, and I haven't yet found out how to change this line ending issue. I did make the other changes, however

**Pull request closed without merging**
